name: Run Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'functime/**'
      - 'pyproject.toml'
      - "tests/**"
      - '.github/workflows/test.yml'
  pull_request:
    types: [ review_requested ]
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[test]"
      - name: Test local functions
        run: pytest tests --benchmark-disable
